### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by MysteryPancake** [MysteryPancake/Phomeme#3]
- [x] add mic input and output (with auto transcription using speech api) AND GREY TEXT FOR BITS OF SPEECH THAT ARE PROCESSING STILL
- [ ] Volume and pitch matching/humanizing
- [ ] Add reverse phonemes at some point
- [ ] Fix punctuation matching so it actually works again
- [ ] add wav and mp3 export and play options in the results
- [ ] add result speech editor - and options in this to disable diphones and triphones and change settings like that and add new stuff and delete stuff
- [ ] add auto-completion telling you whether or not the word will work
- [ ] add multiple input for combined transcripts
- [ ] get all broken website things to work
- [ ] add a way to use emphasis (CMU dictionary uses 0 = none, 1 = most, 2 = a little)
- [ ] convert numbers to words
- [ ] add Final Cut type XML export option maybe
- [ ] audio effects like normalization or silence removal
- [ ] add pitch modification somehow
- [ ] add crossfading
- [ ] add phone alternatives to avoid OOV
- [ ] add automatic click/pop removal
- [ ] add a way to set the audio transcription microphone
- [ ] add a way to set the recording microphone
- [ ] midi parsing support
- [ ] video playing support

After it works properly:
- [ ] maybe do something where you could have a twitch or youtube livestream where you type something and it says it in another voice and the voices rotate every now and then
